toshikingggg/ReservationApp-front

README.md, makefile, package.json, postcss.config.js, src/components/Auth.tsx, src/components/Group.tsx, src/components/Layout.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/pages/select-group.tsx, styles/globals.css, tailwind.config.js, yarn.lock
- ログインページ周りの実装
- tailwind css入れた
=> Login page

.gitignore, src/components/Auth.tsx, src/components/Layout.tsx
=> [add] Connect to login and user creation endpoints

src/components/Auth.tsx, src/pages/select-group.tsx, src/utils/Button.tsx, src/utils/Input.tsx
=> [fix] Split to utils

README.md, src/components/Auth.tsx, src/components/Layout.tsx, src/context/AuthContext.tsx, src/pages/_app.tsx
- 認証関係のState管理用に追加
- リダイレクトは色々あってやむなしLayoutcomponentでしてる
=> [add] AuthContext & redirect

src/components/Auth.tsx, src/components/Group.tsx, src/components/GroupRegister.tsx, src/components/Layout.tsx, src/context/AuthContext.tsx, src/pages/register-group.tsx, src/utils/Button.tsx
- 画面作成
- グループ登録のAPIと繋ぎこみ
- その他デバックの残り削除
=> グループ登録APIと繋ぎこみ

package.json, src/components/Calendar.tsx, src/components/Group.tsx, src/pages/calendar.tsx, src/pages/reservation/[date].tsx, yarn.lock
=> [add] calendar

src/components/Calendar.tsx, src/utils/Modal.tsx
=> [fix]utilにModalを切り分けた

src/components/Auth.tsx, src/components/Dropdown.tsx, src/components/GroupRegister.tsx, src/components/Layout.tsx, src/context/AuthContext.tsx, src/pages/_app.tsx
=> [fix]keep state

package.json, src/components/Calendar.tsx, src/components/SelectGroup.tsx, src/hooks/useOrgUsers.ts, src/pages/calendar.tsx, src/pages/select-group.tsx, src/utils/DateAndTimePickers.tsx, yarn.lock
=> [add]予約モーダル＆繋ぎこみ

src/components/Calendar.tsx, src/hooks/useReservations.ts, src/pages/calendar.tsx, src/utils/DateAndTimePickers.tsx
=> [add]予約取得実装

src/components/Dropdown.tsx, src/components/MyReservation.tsx, src/hooks/useMyReservations.ts, src/pages/my-reservation.tsx
=> [add]delete api繋ぎこみ

src/components/Calendar.tsx, src/components/MyReservation.tsx, src/hooks/useMyReservations.ts, src/hooks/useReservations.ts, src/utils/DateAndTimePickers.tsx
=> [add]edit reservation

src/components/RegisterSpace.tsx
=> [fix]複数のスペースを追加できるように修正

src/components/Calendar.tsx, src/components/Dropdown.tsx, src/hooks/useOrgSpaces.ts, src/pages/calendar.tsx, src/utils/ViewCard.tsx
=> [add]select space component

src/components/Calendar.tsx, src/context/ ReservationStateContext.tsx, src/hooks/useReservations.ts, src/pages/calendar.tsx, src/utils/DateAndTimePickers.tsx, src/utils/ViewCard.tsx
- SpaceIdでフィルターかけたかったのでContext追加
=> [add]SpaceContext

src/components/Calendar.tsx, src/pages/calendar.tsx, src/utils/DateAndTimePickers.tsx, src/utils/ViewCard.tsx
=> [fix]calendar style

src/components/Auth.tsx, src/components/Dropdown.tsx, src/components/GroupRegister.tsx, src/components/Layout.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/pages/login.tsx, src/utils/DateAndTimePickers.tsx, src/utils/Input.tsx
- パスワード見えるようにする
- loginのパス変える
- リダイレクト若干変更
=> [fix]layout

package.json, src/components/Atoms/Loading.tsx, src/components/Organiams/DateAndTimePickers.tsx, src/components/Templates/Calendar.tsx, src/components/Templates/MyReservation.tsx, src/components/Templates/SelectGroup.tsx, src/hooks/useUser.ts, src/pages/calendar/[orgId].tsx, src/pages/my-reservation.tsx, src/pages/mypage.tsx, yarn.lock
- Loading component追加
- memoの追加
=> Design Fix

src/components/Organiams/DetailReservation.tsx, src/components/Templates/Calendar.tsx, src/components/Templates/MyReservation.tsx, src/pages/mypage.tsx, src/utils/selectedDateConverter.ts
=> [fix]予約詳細修正

src/components/Atoms/Button.tsx, src/components/Atoms/Loading.tsx, src/components/Organiams/DateAndTimePickers.tsx, src/components/Templates/Calendar.tsx, src/components/Templates/Dropdown.tsx, src/components/Templates/SelectGroup.tsx, src/hooks/useUser.ts, src/pages/calendar/[orgId].tsx, src/pages/mypage.tsx, src/utils/fetch.ts
=> [fix]desgin

src/components/Templates/MyReservation.tsx, src/pages/info/terms.tsx
=> [fix]レイアウト調整

src/components/Modules/OrgListItem.tsx, src/components/Modules/ReservationListItem.tsx, src/components/Organiams/PagenatedList.tsx, src/components/Organiams/PaginatedList.tsx, src/components/Organiams/SearchBox.tsx, src/components/Templates/MyReservation.tsx, src/components/Templates/SelectGroup.tsx
下記の２つにページネーション追加
- 自分の予約確認画面
- 団体検索
※API最新にしてね
=> ページネーション追加
